Repository ipt-cryptolabs/fi-labs-2022, pull requests merged in 2022-06, with the labels that each got.

#27 [CP-3] L.Yemets (FI-93)
  cp_3/emets_fi-93_cp3/kripta3.docx
  cp_3/emets_fi-93_cp3/src/com/company/03.txt
  cp_3/emets_fi-93_cp3/src/com/company/Main.java
  cp_3/emets_fi-93_cp3/src/com/company/Possible keys.txt
Labels: incomplete_code

#12 [CP-1] M. Martynova (FI-93)
  cp_1/martynova_fi-93_cp1/.DS_Store
  cp_1/martynova_fi-93_cp1/.gitignore
  cp_1/martynova_fi-93_cp1/MasterMargo.txt
  cp_1/martynova_fi-93_cp1/charts.pdf
  cp_1/martynova_fi-93_cp1/program.py
  cp_1/martynova_fi-93_cp1/protocol.pdf
Labels: needs_cleanup

#7 [CP-2] L.Yemets (FI-93)
  cp_2/emets_fi-93_cp2/Main.java
  cp_2/emets_fi-93_cp2/cipher3.txt
  cp_2/emets_fi-93_cp2/clearText.txt
  cp_2/emets_fi-93_cp2/kripta2.pdf
Labels: incomplete_results

#28 [CP-2] M. Martynova (FI-93)
  cp_2/martynova_fi-93_cp2/.gitignore
  cp_2/martynova_fi-93_cp2/Shakespear.txt
  cp_2/martynova_fi-93_cp2/ciphertext.txt
  cp_2/martynova_fi-93_cp2/program2.py
  cp_2/martynova_fi-93_cp2/protocol2.pdf
  cp_2/martynova_fi-93_cp2/симкрипт2.xlsx
Labels: incomplete_results

#32 [CP-1] Koroban (FI-94)
  cp_1/koroban_fi-94_cp1/lab1.java
  cp_1/koroban_fi-94_cp1/text00.txt
  cp_1/koroban_fi-94_cp1/протокол 1.pdf
Labels: needs_cleanup, incomplete_results

#41 [CP-2] Kutsenko (FI-94), Misnik (FI-94)
  cp_2/cp_2_Kutsenko_Misnik_fi-94/Lab2.pdf
  cp_2/cp_2_Kutsenko_Misnik_fi-94/Open.txt
  cp_2/cp_2_Kutsenko_Misnik_fi-94/main.py
  cp_2/cp_2_Kutsenko_Misnik_fi-94/text.txt
Labels: incomplete_results

#37 [CP-1] Kutsenko (FI-94), Misnik (FI-94)
  cp_1/cp_1_Kutsenko_Misnik_fi-94/Lab1.pdf
  cp_1/cp_1_Kutsenko_Misnik_fi-94/Source.cpp
Labels: report_cleanup

#38 [CP-1]Orzhahivskiy(FI-93)
  cp_1/Orzhahivskiy_Max_Fi-93_cp1/Protokol_laba_1_Orzhahivskiy_Max_FI-93.pdf
  cp_1/Orzhahivskiy_Max_Fi-93_cp1/Source.cpp
  cp_1/Orzhahivskiy_Max_Fi-93_cp1/Text.txt
Labels: needs_report

#43 [CP3]Orzhahivskiy(FI-93)
  cp_3/Orzhahivsky_Fi-93_cp3/Protokol_3_Laba_Orzhahivskiy_Max_FI-93.pdf
  cp_3/Orzhahivsky_Fi-93_cp3/Shifr.txt
  cp_3/Orzhahivsky_Fi-93_cp3/Source.cpp
Labels: needs_report
